import { BeatleaderModifierRating } from "./modifierRating";
import { BeatleaderModifier } from "./modifiers";

export type BeatleaderDifficulty = {
  id: number;
  value: number;
  mode: number;
  difficultyName: string;
  modeName: string;
  status: number;
  modifierValues: BeatleaderModifier;
  modifiersRating: BeatleaderModifierRating;
  nominatedTime: number;
  qualifiedTime: number;
  rankedTime: number;
  stars: number;
  predictedAcc: number;
  passRating: number;
  accRating: number;
  techRating: number;
  type: number;
  njs: number;
  nps: number;
  notes: number;
  bombs: number;
  walls: number;
  maxScore: number;
  duration: number;
  requirements: number;
};
